version: '3.8'

services:
  # Service 1: The Database (Downloads a pre-made image)
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: gridguardian_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gridguardian
    ports:
      - "5432:5432"
    volumes:
      - gridguardian_data:/var/lib/postgresql/data
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Service 2: Your C# Backend (Builds from your Dockerfile)
  backend:
    build:
      context: ./backend         # Look inside the 'backend' folder...
      dockerfile: Dockerfile     # ...and find the file named 'Dockerfile'
    container_name: gridguardian_api
    restart: always
    ports:
      - "5078:8080"              # Map Local Port 5078 -> Container Port 8080
    environment:
      # CRITICAL: This overrides appsettings.json to talk to the 'timescaledb' container
      - ConnectionStrings__DefaultConnection=Host=timescaledb;Port=5432;Database=gridguardian;Username=admin;Password=password123
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - timescaledb              # Wait for DB to start before starting Backend

volumes:
  gridguardian_data: